### ISSUE TITLE
not good result

### ISSUE THREAD

**Issue by SeekPoint** [kartik144/Text_Imputation#16]
@gpu04:~/Text_Imputation$ python3 main.py --model_left models/LM_g1b_77_batch64_em_600.pt --model_right models-ep1000-revLM/revLM_g1b_77_batch64_em_600.pt --model_bi models-ep1000-bidi/bidi_g1b_77_batch64_em_600.pt --model_attn  models-ep1000-biatt/biatt_g1b_77_batch64_em_600.pt --dict_attn Dictionary/dict.pt
WARNING: You have a CUDA device, so you should probably run with --cuda
Enter sentence (Enter $TOP to stop)
hi
## No blank inputted!! ##

stack expects a non-empty TensorList
Enter sentence (Enter $TOP to stop)
hit
## No blank inputted!! ##

stack expects a non-empty TensorList
Enter sentence (Enter $TOP to stop)
say hello to
## No blank inputted!! ##

stack expects a non-empty TensorList
Enter sentence (Enter $TOP to stop)
say hello to
## No blank inputted!! ##

stack expects a non-empty TensorList
Enter sentence (Enter $TOP to stop)

**Comment by kartik144** [comment]
You have to input sentence as:
```
The weather was _ _ _ yesterday. 
```
i.e. input a whole sentence with a blank where word has to be filled in. Blank is inputted by using three underscore(_) symbols.

Not entering any blanks would give an exception!

**Comment by SeekPoint** [comment]
expected a non-empty list of Tensors
Enter sentence (Enter $TOP to stop)
how about this ___ ___ ___
shape '[-1, 7240]' is invalid for input of size 31460

**Comment by kartik144** [comment]
The model is currently tuned to work with only one missing word in the sentence at the moment.
Can you try something like:

They went to the ___ to get some fish

**Comment by SeekPoint** [comment]
They went to the ___ to get some fish
shape '[-1, 7240]' is invalid for input of size 39325
Enter sentence (Enter $TOP to stop)

**Comment by kartik144** [comment]
Seems like an issue with the dictionary size you are using for prediction and the dictionary size of the saved model. Can you please go through the input dictionary and the saved model to ensure that they are from the same corpus?

By preliminary checking this error could originate from [here](https://github.com/kartik144/Text_Imputation/blob/master/main.py#L80):
```
output_flat_left = outputs_left.view(-1, ntokens)[-1]
```
due to mismatch of dictionary size of output of model and saved dict size. 

Can you please check all the inputs are consistent? 

If error persists, could you possibly deep dive and give exact source/line of code from where the error might be originating? It's hard to guess the source of exception from just the error message
